"""
Report generator — orchestrates the full report pipeline.

Changes vs. original:
  - Section 4 (AI Executive Summary) now calls the real OpenVINO ChatEngine
    when `include_ai_summary=True` instead of returning a hardcoded string.
  - Falls back to a statistics-based plaintext summary when the LLM is in
    mock mode (model not loaded), so the report is always useful.
"""

from __future__ import annotations

import asyncio
import logging
from typing import Optional

from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from sqlalchemy.orm import selectinload

import uuid

from helios.models.project import Project
from helios.models.finding import Finding
from helios.core.reports.risk_calculator import calculate_project_risk
from helios.core.reports.formatters.markdown import generate_markdown_report

logger = logging.getLogger(__name__)

# Severity ordering for sort
_SEVERITY_ORDER = {"critical": 0, "high": 1, "medium": 2, "low": 3, "info": 4}


async def _generate_ai_summary(project: Project, findings, risk_data: dict) -> str:
    """
    Call the OpenVINO LLM to generate a concise executive summary.
    Returns a fallback statistics string if the model is not loaded.
    """
    try:
        from helios.infrastructure.openvino_runtime import OpenVINORuntime
        runtime = OpenVINORuntime()

        if not runtime.pipeline:
            # Model not loaded — return a meaningful stats-based fallback
            raise RuntimeError("Model not loaded — using fallback summary.")

        n_critical = sum(1 for f in findings if (f.severity or "").lower() == "critical")
        n_high = sum(1 for f in findings if (f.severity or "").lower() == "high")
        n_medium = sum(1 for f in findings if (f.severity or "").lower() == "medium")

        context = (
            f"Project: {project.name}\n"
            f"Total findings: {len(findings)}\n"
            f"Critical: {n_critical}, High: {n_high}, Medium: {n_medium}\n"
            f"Overall risk level: {risk_data.get('level', 'Unknown')}\n"
            f"Risk score: {risk_data.get('score', 0):.1f}/10\n\n"
            f"Top findings:\n"
        )
        for f in findings[:5]:
            context += f"  - [{f.severity.upper()}] {f.title}\n"

        prompt = (
            f"<|system|>\n"
            "You are an expert penetration tester writing a professional security report. "
            "Write a concise executive summary (3-4 paragraphs) based on the findings below. "
            "Be factual, actionable, and use professional language. "
            "Do NOT invent findings that are not listed.\n"
            "<|end|>\n"
            f"<|user|>\n{context}\nWrite the executive summary.<|end|>\n"
            "<|assistant|>\n"
        )

        from helios.infrastructure.openvino_runtime import GenerationConfig
        gen_config = GenerationConfig(max_new_tokens=512, temperature=0.2, do_sample=False)

        tokens = []
        async for token in runtime.generate_stream(prompt, gen_config):
            tokens.append(token)
        ai_text = "".join(tokens).strip()

        if not ai_text:
            raise RuntimeError("Empty LLM response.")

        return f"**AI Executive Summary (generated by HELIOS AI):**\n\n{ai_text}"

    except Exception as exc:
        logger.warning(f"AI summary generation skipped: {exc}")
        # Fallback: generate a statistical summary without LLM
        return _fallback_summary(project, findings, risk_data)


def _fallback_summary(project: Project, findings, risk_data: dict) -> str:
    """Statistics-based summary used when the LLM model is not loaded."""
    severity_counts = {}
    for f in findings:
        sev = (f.severity or "info").lower()
        severity_counts[sev] = severity_counts.get(sev, 0) + 1

    lines = [
        "**Executive Summary:**\n",
        f"The security assessment of **{project.name}** identified a total of "
        f"**{len(findings)} findings** across the assessed scope.\n",
    ]
    for sev in ("critical", "high", "medium", "low", "info"):
        count = severity_counts.get(sev, 0)
        if count:
            lines.append(f"- **{sev.capitalize()}**: {count}")

    lines.append(
        f"\nThe overall risk posture is assessed as **{risk_data.get('level', 'Unknown')}** "
        f"(score: {risk_data.get('score', 0):.1f}/10). "
        "Immediate remediation of critical and high severity findings is strongly recommended."
    )
    return "\n".join(lines)


async def generate_report(
    db: AsyncSession,
    project_id: uuid.UUID,
    include_ai_summary: bool = False,
) -> str:
    """Orchestrates the full report generation pipeline."""

    # 1. Fetch Project
    result = await db.execute(select(Project).filter_by(id=project_id))
    project = result.scalars().first()
    if not project:
        raise ValueError("Project not found.")

    # 2. Fetch Findings with Evidence
    result = await db.execute(
        select(Finding)
        .filter_by(project_id=project_id)
        .options(selectinload(Finding.evidence))
    )
    findings = result.scalars().all()

    # Sort: Critical > High > Medium > Low > Info
    findings = sorted(
        findings,
        key=lambda f: _SEVERITY_ORDER.get((f.severity or "info").lower(), 5),
    )

    # 3. Calculate Risk
    risk_data = calculate_project_risk(findings)

    # 4. Generate AI Executive Summary (real LLM or statistics fallback)
    ai_summary = ""
    if include_ai_summary:
        ai_summary = await _generate_ai_summary(project, findings, risk_data)

    # 5. Format to Markdown
    return generate_markdown_report(project, findings, risk_data, ai_summary)
